/**
 * Type: Configuration
 * Description: A library that contains a key-value object to be used as constants.
 */

//OLD LIB FOR USE WITH MODBUS ADAPTER 
const modbusLib = {
    FUNCTION_CODES:{
        MODBUS_FUNC_READ_COILS: 1,
        MODBUS_FUNC_READ_DISCRETE_INPUTS: 2,
        MODBUS_FUNC_READ_HOLDING_REGISTERS: 3,
        MODBUS_FUNC_READ_INPUT_REGISTERS: 4,
        MODBUS_FUNC_WRITE_SINGLE_COIL: 5,
        MODBUS_FUNC_WRITE_SINGLE_REGISTER: 6,
        MODBUS_FUNC_WRITE_MULTIPLE_COILS: 15,
        MODBUS_FUNC_WRITE_MULTIPLE_REGISTERS: 16,
        MODBUS_FUNC_MASK_WRITE_REGISTER: 22,
        MODBUS_FUNC_READ_WRITE_MULTIPLE_REGISTERS: 23,
        MODBUS_FUNC_READ_FIFO_QUEUE: 24
    },
    EXCEPTION_CODES:{
        MODBUS_EXCEPTION_ILLEGAL_FUNCTION: 1,
        MODBUS_EXCEPTION_ILLEGAL_DATA_ADDRESS: 2,
        MODBUS_EXCEPTION_ILLEGAL_DATA_VALUE: 3,
        MODBUS_EXCEPTION_SERVER_DEVICE_FAILURE: 4,
        MODBUS_EXCEPTION_ACKNOWLEDGE: 5,
        MODBUS_EXCEPTION_SERVER_DEVICE_BUSY: 6,
        MODBUS_EXCEPTION_MEMORY_PARITY_ERROR: 8,
        MODBUS_EXCEPTION_GATEWAY_PATH_UNAVAILABLE: 10,
        MODBUS_EXCEPTION_GATEWAY_TARGET_DEVICE_FAILED_TO_RESPOND: 11
    }
};
